<Project Sdk="Microsoft.NET.Sdk">

  <!-- This is a packaging-only project for native SQLCipher binaries -->

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NoBuild>true</NoBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecFile>e_sqlcipher.native.nuspec</NuspecFile>
    <NuspecProperties>version=$(Version)</NuspecProperties>
  </PropertyGroup>

</Project>
